/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simple_calculator;

/**
 *
 * @author User
 */
public class viwe extends javax.swing.JFrame {

    /**
     * Creates new form viwe
     */
    public viwe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viwe_pannel_1 = new javax.swing.JPanel();
        Num_1_lbl = new javax.swing.JLabel();
        Num_2_lbl = new javax.swing.JLabel();
        Num_1 = new javax.swing.JTextField();
        Num_2 = new javax.swing.JTextField();
        Result = new javax.swing.JLabel();
        Btn_Subtraction = new javax.swing.JButton();
        Btn_Add = new javax.swing.JButton();
        Btn_Divide = new javax.swing.JButton();
        Btn_Multiply = new javax.swing.JButton();
        Result_Viwe = new javax.swing.JLabel();
        Btn_Clear = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Opr_View = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        viwe_pannel_1.setBackground(new java.awt.Color(51, 51, 51));

        Num_1_lbl.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Num_1_lbl.setForeground(new java.awt.Color(204, 204, 204));
        Num_1_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Num_1_lbl.setText("Number 1");

        Num_2_lbl.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Num_2_lbl.setForeground(new java.awt.Color(204, 204, 204));
        Num_2_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Num_2_lbl.setText("Number 2");

        Num_1.setBackground(new java.awt.Color(204, 204, 204));
        Num_1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Num_1.setForeground(new java.awt.Color(0, 0, 0));
        Num_1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Num_2.setBackground(new java.awt.Color(204, 204, 204));
        Num_2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Num_2.setForeground(new java.awt.Color(0, 0, 0));
        Num_2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_2ActionPerformed(evt);
            }
        });

        Result.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Result.setForeground(new java.awt.Color(204, 204, 204));
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setText("Result");

        Btn_Subtraction.setBackground(new java.awt.Color(0, 102, 102));
        Btn_Subtraction.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Btn_Subtraction.setText("-");
        Btn_Subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubtractionActionPerformed(evt);
            }
        });

        Btn_Add.setBackground(new java.awt.Color(0, 102, 102));
        Btn_Add.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Btn_Add.setText("+");
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        Btn_Divide.setBackground(new java.awt.Color(0, 102, 102));
        Btn_Divide.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Btn_Divide.setText("/");
        Btn_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DivideActionPerformed(evt);
            }
        });

        Btn_Multiply.setBackground(new java.awt.Color(0, 102, 102));
        Btn_Multiply.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Btn_Multiply.setText("*");
        Btn_Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MultiplyActionPerformed(evt);
            }
        });

        Result_Viwe.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Result_Viwe.setForeground(new java.awt.Color(204, 204, 204));
        Result_Viwe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result_Viwe.setText("0");

        Btn_Clear.setBackground(new java.awt.Color(153, 102, 0));
        Btn_Clear.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Btn_Clear.setText("Ac");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 204, 204));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Simple Calculator");

        Opr_View.setBackground(new java.awt.Color(255, 255, 255));
        Opr_View.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Opr_View.setForeground(new java.awt.Color(255, 255, 255));
        Opr_View.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opr_View.setText(" ");

        javax.swing.GroupLayout viwe_pannel_1Layout = new javax.swing.GroupLayout(viwe_pannel_1);
        viwe_pannel_1.setLayout(viwe_pannel_1Layout);
        viwe_pannel_1Layout.setHorizontalGroup(
            viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viwe_pannel_1Layout.createSequentialGroup()
                                .addComponent(Btn_Subtraction)
                                .addGap(34, 34, 34)
                                .addComponent(Btn_Multiply)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viwe_pannel_1Layout.createSequentialGroup()
                                .addComponent(Btn_Add)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Divide)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                                    .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(Num_1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Opr_View, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(Num_2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Result_Viwe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viwe_pannel_1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        viwe_pannel_1Layout.setVerticalGroup(
            viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viwe_pannel_1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Title)
                .addGap(29, 29, 29)
                .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opr_View))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_1_lbl)
                    .addComponent(Num_2_lbl))
                .addGap(18, 18, 18)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Result_Viwe)
                .addGap(25, 25, 25)
                .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Clear)
                    .addComponent(Btn_Add)
                    .addComponent(Btn_Divide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viwe_pannel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Multiply)
                    .addComponent(Btn_Subtraction))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viwe_pannel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viwe_pannel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Subtraction Session
    private void Btn_SubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubtractionActionPerformed
        int num_1 = Integer.parseInt(Num_1.getText());
        int num_2 = Integer.parseInt(Num_2.getText());
        
        int result = num_1 - num_2;
        
        Result_Viwe.setText(String.valueOf(result));
        Opr_View.setText("-");
    }//GEN-LAST:event_Btn_SubtractionActionPerformed
//Addition Session
    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        int num_1 = Integer.parseInt(Num_1.getText());
        int num_2 = Integer.parseInt(Num_2.getText());
        
        int result = num_1 + num_2;
        
        Result_Viwe.setText(String.valueOf(result));
        Opr_View.setText("+");
    }//GEN-LAST:event_Btn_AddActionPerformed
//Divide Session
    private void Btn_DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DivideActionPerformed
        Double num_1 = Double.parseDouble(Num_1.getText());
        Double num_2 = Double.parseDouble(Num_2.getText());
        
        Double result = num_1 / num_2;
        
        Result_Viwe.setText(String.valueOf(result));
        Opr_View.setText("÷");
    }//GEN-LAST:event_Btn_DivideActionPerformed
//Multiply Session
    private void Btn_MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MultiplyActionPerformed
        int num_1 = Integer.parseInt(Num_1.getText());
        int num_2 = Integer.parseInt(Num_2.getText());
        
        int result = num_1 * num_2;
        
        Result_Viwe.setText(String.valueOf(result));
        Opr_View.setText("x");
    }//GEN-LAST:event_Btn_MultiplyActionPerformed
//Clear View Session
    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        Num_1.setText("");
        Num_2.setText("");
        Result_Viwe.setText("0");
        Opr_View.setText(" ");
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viwe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Divide;
    private javax.swing.JButton Btn_Multiply;
    private javax.swing.JButton Btn_Subtraction;
    private javax.swing.JTextField Num_1;
    private javax.swing.JLabel Num_1_lbl;
    private javax.swing.JTextField Num_2;
    private javax.swing.JLabel Num_2_lbl;
    private javax.swing.JLabel Opr_View;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel Result_Viwe;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel viwe_pannel_1;
    // End of variables declaration//GEN-END:variables
}
